<?php

namespace Tofuma\EnvExporter;

use DateTimeImmutable;
use DateTimeInterface;
use RuntimeException;

class EnvExporter
{
    /**
     * Generate a .env file from an example template using system environment variables.
     *
     * @param string $examplePath Path to the example env file (.env.example)
     * @param string $outputPath Path to write the generated .env file
     * @param bool $returnPairs If true, returns the generated key-value pairs instead of writing to file
     * @return array|null Returns array of pairs if $returnPairs is true, null otherwise
     * @throws RuntimeException On file read/write errors
     */
    public static function generate(string $examplePath, string $outputPath, bool $returnPairs = false): ?array
    {
        if (!is_file($examplePath) || !is_readable($examplePath)) {
            throw new RuntimeException("Example env file not found or not readable: {$examplePath}");
        }

        $exampleLines = @file($examplePath, FILE_IGNORE_NEW_LINES);
        if ($exampleLines === false) {
            throw new RuntimeException("Failed to read example env file: {$examplePath}");
        }

        $keys = [];
        foreach ($exampleLines as $line) {
            $key = self::parseKeyFromLine($line);
            if ($key !== null) {
                $keys[$key] = true;
            }
        }

        $pairs = [];
        foreach (array_keys($keys) as $key) {
            $val = getenv($key);
            if ($val !== false) {
                $pairs[$key] = (string)$val;
            }
        }

        if ($returnPairs) {
            return $pairs;
        }

        self::writeEnvFile($outputPath, $pairs, $examplePath);
        return null;
    }

    /**
     * Parse a line from an env file and return the KEY if present.
     */
    private static function parseKeyFromLine(string $line): ?string
    {
        $trim = trim($line);
        if ($trim === '' || $trim[0] === '#' || $trim[0] === ';') {
            return null;
        }

        if (stripos($trim, 'export ') === 0) {
            $trim = trim(substr($trim, 7));
        }

        if (preg_match('/^([A-Za-z_][A-Za-z0-9_]*)\s*=/', $trim, $m)) {
            return $m[1];
        }

        return null;
    }

    /**
     * Render a value for .env output with proper escaping.
     */
    private static function renderValue(string $value): string
    {
        if ($value !== '' && preg_match('/^[A-Za-z0-9._\-\/:@]+$/', $value)) {
            return $value;
        }

        $escaped = str_replace(["\\", "\"", "\r"], ["\\\\", "\\\"", ""], $value);
        $escaped = preg_replace('/\$/', '\\$', $escaped);

        return '"' . $escaped . '"';
    }

    /**
     * Ensure directory exists for a file path.
     */
    private static function ensureDir(string $filePath): void
    {
        $dir = dirname($filePath);
        if (!is_dir($dir)) {
            if (!@mkdir($dir, 0775, true) && !is_dir($dir)) {
                throw new RuntimeException("Failed to create directory: {$dir}");
            }
        }
    }

    /**
     * Write the .env file atomically.
     */
    private static function writeEnvFile(string $outputPath, array $pairs, string $examplePath): void
    {
        $now = (new DateTimeImmutable('now'))->format(DateTimeInterface::RFC3339);
        $header = [
            '# ----------------------------------------------------------------------',
            '# Generated by tofuma/env-exporter',
            '# Source example: ' . $examplePath,
            '# Generated at:   ' . $now,
            '# Only variables present in the current environment are included.',
            '# ----------------------------------------------------------------------',
        ];

        $outLines = $header;
        foreach ($pairs as $k => $v) {
            $outLines[] = $k . '=' . self::renderValue($v);
        }
        $out = implode(PHP_EOL, $outLines) . PHP_EOL;

        self::ensureDir($outputPath);

        $tmp = $outputPath . '.tmp.' . bin2hex(random_bytes(6));
        if (@file_put_contents($tmp, $out) === false) {
            @unlink($tmp);
            throw new RuntimeException("Failed to write temporary file: {$tmp}");
        }

        if (!@rename($tmp, $outputPath)) {
            if (!@copy($tmp, $outputPath)) {
                @unlink($tmp);
                throw new RuntimeException("Failed to move temp file to output: {$outputPath}");
            }
            @unlink($tmp);
        }
    }

    /**
     * Get the count of generated pairs (useful after generate with returnPairs=false).
     */
    public static function generateAndReport(string $examplePath, string $outputPath): int
    {
        $pairs = self::generate($examplePath, $outputPath, true);
        self::writeEnvFile($outputPath, $pairs, $examplePath);
        return count($pairs);
    }
}
